### ISSUE TITLE
Issues with Running on Win 10

### ISSUE THREAD

**Issue by davidehnis** [nanunintan/Alloy2Cs#2]
I've followed the instructions, including downloading and installing Haskell.  I am receiving the following error:

2 of 8] Compiling Alloy.AST        ( Alloy\AST.hs, Alloy\AST.o )

Alloy\AST.hs:7:1: error:
    Could not find module `Data.Generics'
    Use -v to see a list of the files searched for.
  |
7 | import Data.Generics
  | ^^^^^^^^^^^^^^^^^^^^

**Comment by nanunintan** [comment]
Hi David, sorry for the delay.
I was able to reproduce the error and after some research I figured out that is related with some conflicts between the dependencies.

syb must be installed outside the sandbox. I have updated the instructions to reflect this change.
